// <auto-generated />
using System;
using ExamenUnidad2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenUnidad2.Migrations
{
    [DbContext(typeof(PersonDBContext))]
    [Migration("20260327003850_CreatingDatabase")]
    partial class CreatingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ExamenUnidad2.Entities.DetallePlanilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<float>("Bonificaciones")
                        .HasColumnType("REAL")
                        .HasColumnName("Bonificaciones");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comentarios");

                    b.Property<float>("Deducciones")
                        .HasColumnType("REAL")
                        .HasColumnName("Deducciones");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmpleadoId");

                    b.Property<float>("HorasExtras")
                        .HasColumnType("REAL")
                        .HasColumnName("Horas_Extras");

                    b.Property<float>("MontoHorasExtra")
                        .HasColumnType("REAL")
                        .HasColumnName("Monto_Horas_Extra");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PlanillaId");

                    b.Property<float>("SalarioBase")
                        .HasColumnType("REAL")
                        .HasColumnName("SalarioBase");

                    b.Property<float>("SalarioNeto")
                        .HasColumnType("REAL")
                        .HasColumnName("SalarioNeto");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("DetallePlanillas");
                });

            modelBuilder.Entity("ExamenUnidad2.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Apellido");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Departamento");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Documento");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaContratacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<string>("PuestoTrabajo")
                        .HasColumnType("TEXT")
                        .HasColumnName("PuestoTrabajo");

                    b.Property<float>("SalarioBase")
                        .HasColumnType("REAL")
                        .HasColumnName("SalarioBase");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ExamenUnidad2.Entities.Planilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaPago");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Periodo");

                    b.HasKey("Id");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("ExamenUnidad2.Entities.DetallePlanilla", b =>
                {
                    b.HasOne("ExamenUnidad2.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenUnidad2.Entities.Planilla", "Planilla")
                        .WithMany()
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Planilla");
                });
#pragma warning restore 612, 618
        }
    }
}
